version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.0.0
    container_name: es-elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - docker_elk
  kibana:
    image: kibana:7.0.0
    container_name: es-kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch
    networks:
      - docker_elk
networks:
  docker_elk:
    driver: bridge